<!DOCTYPE html>
<html lang="id" data-user-theme="light" data-user-lang="id">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Dashboard Klien - Kantor Notaris/PPAT</title>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('css/user-dashboard.css') }}?v={{ filemtime(public_path('css/user-dashboard.css')) }}">
</head>
<body>
<header class="client-header">
    <div class="client-brand"><div class="client-brand-logos"><img src="{{ asset('images/garuda_logo.png') }}" alt="Garuda"><img src="{{ asset('images/logo-ini-1.jpg') }}" alt="INI"><img src="{{ asset('images/PPAT.png') }}" alt="PPAT"></div><div><small>KANTOR NOTARIS/PPAT</small><strong>NI LUH PUTU SURYA MIRA YANTI, SH., M.Kn.</strong></div></div>
    <nav class="client-public-links"><a href="{{ route('public.home') }}">Beranda</a><a href="{{ route('public.home') }}#layanan">Layanan</a><a href="{{ route('public.home') }}#tracking">Tracking</a><a href="{{ route('public.home') }}#kontak">Kontak</a></nav>
    <div class="client-header-actions"><div class="notification-popover-wrap"><button class="icon-button" data-notification-toggle aria-label="Notifikasi" aria-expanded="false"><span class="bell-icon"></span><b>3</b></button><section class="notification-popover" data-notification-popover aria-hidden="true"><header><div><strong>Notifikasi</strong><small>3 belum dibaca</small></div><button type="button" data-mark-notifications-read>Tandai dibaca</button></header><div class="notification-popover-list"><button type="button" data-notification-item="applications"><i class="blue"></i><span><strong>Status berkas diperbarui</strong><small>BRK-2026-014 memasuki tahap pengecekan sertifikat.</small><time>Hari ini, 10:20</time></span></button><button type="button" data-notification-item="documents"><i class="amber"></i><span><strong>Dokumen tambahan diminta</strong><small>Unggah SPPT PBB terbaru untuk BRK-2026-021.</small><time>Kemarin, 14:05</time></span></button><button type="button" data-notification-item="appointments"><i class="green"></i><span><strong>Jadwal temu dibuat</strong><small>Penandatanganan AJB pada 24 Juni 2026.</small><time>19 Juni 2026</time></span></button></div><footer><button type="button" data-open-all-notifications>Lihat Semua Notifikasi</button></footer></section></div><button class="profile-button"><span>KA</span><div><strong>Komang Arya</strong><small>Klien</small></div></button><button class="mobile-menu-button" data-sidebar-toggle aria-label="Buka menu"><span></span><span></span><span></span></button></div>
</header>
<div class="client-layout">
<aside class="client-sidebar" id="clientSidebar"><div class="sidebar-user"><span>KA</span><div><strong>Komang Arya Pratama</strong><small>USR-2026-0014</small></div></div><nav class="sidebar-nav" aria-label="Navigasi dashboard"><button class="active" data-section="dashboard"><img src="{{ asset('images/nav-icons/profil.svg') }}" alt=""><span>Dashboard</span></button><button data-section="applications"><img src="{{ asset('images/nav-icons/berkas.svg') }}" alt=""><span>Pengajuan Saya</span><b>3</b></button><button data-section="documents"><img src="{{ asset('images/nav-icons/pendaftaran.svg') }}" alt=""><span>Upload Dokumen</span><b>1</b></button><button data-section="appointments"><img src="{{ asset('images/nav-icons/kontak.svg') }}" alt=""><span>Jadwal Temu</span></button><button data-section="settings"><img src="{{ asset('images/nav-icons/layanan.svg') }}" alt=""><span>Pengaturan</span></button></nav><button class="sidebar-logout" data-logout>Keluar</button></aside>
<main class="client-main">
<section class="dashboard-section active" data-dashboard-section="dashboard"><div class="page-heading"><div><p>RINGKASAN AKUN</p><h1>Halo, Komang Arya</h1><span>Pantau pengajuan, dokumen, dan jadwal Anda dalam satu tempat.</span></div><button class="primary-action" data-open-section="new-application">+ Buat Pengajuan</button></div><div class="stats-grid"><article><i class="navy">A</i><div><small>Total Pengajuan</small><strong>4</strong><p>+1 bulan ini</p></div></article><article><i class="blue">P</i><div><small>Sedang Diproses</small><strong>2</strong><p>50% pengajuan</p></div></article><article><i class="green">S</i><div><small>Selesai</small><strong>1</strong><p>Siap diambil</p></div></article><article><i class="amber">!</i><div><small>Menunggu Dokumen</small><strong>1</strong><p>Perlu tindakan</p></div></article><article><i class="purple">J</i><div><small>Jadwal Mendatang</small><strong>1</strong><p>24 Juni 2026</p></div></article></div><div class="dashboard-columns"><section class="panel recent-activity"><header><div><h2>Pengajuan Saya</h2><span>Ringkasan pengajuan yang perlu Anda pantau</span></div><button data-open-section="applications">Lihat Semua</button></header><div class="activity-list"><article><i class="blue"></i><div><strong>BRK-2026-014 · PPJB</strong><p>Sedang diproses pada tahap Penandatanganan AJB.</p><time>Progress 67% · Estimasi 7–11 hari kerja</time></div></article><article><i class="amber"></i><div><strong>BRK-2026-021 · Akta Hibah</strong><p>Menunggu SPPT PBB terbaru untuk melanjutkan validasi pajak.</p><time>Progress 38% · Perlu tindakan</time></div></article><article><i class="green"></i><div><strong>BRK-2026-025 · Roya</strong><p>Pengajuan telah selesai dan dokumen siap diambil.</p><time>Selesai 9 Juni 2026</time></div></article></div></section><section class="panel upcoming-card"><h2>Jadwal Terdekat</h2><div class="date-tile"><strong>24</strong><span>JUN<br>2026</span></div><h3>Penandatanganan AJB</h3><p>Selasa, 10.00 WITA</p><span>Kantor Notaris/PPAT</span><button data-open-section="appointments">Lihat Jadwal</button></section></div></section>

<section class="dashboard-section" data-dashboard-section="applications"><div class="page-heading"><div><p>MONITORING BERKAS</p><h1>Pengajuan Saya</h1><span>Pantau seluruh pengajuan dan progres penyelesaiannya.</span></div><button class="primary-action" data-open-section="new-application">+ Buat Pengajuan</button></div><div class="filter-bar"><input type="search" placeholder="Cari nomor registrasi atau layanan"><select><option>Semua Status</option><option>Diproses</option><option>Selesai</option><option>Menunggu Dokumen</option></select></div><div class="application-list">
<article class="application-card"><header><div><small>BRK-2026-014</small><h3>Perjanjian Pengikatan Jual Beli / PPJB</h3></div><span class="status-badge processing">Sedang Diproses</span></header><div class="application-meta"><span>Tanggal Pengajuan<strong>10 Juni 2026</strong></span><span>Status Saat Ini<strong>Penandatanganan AJB</strong></span><span>Estimasi Selesai<strong>7-11 hari kerja</strong></span></div><div class="progress-row"><div><span>Progress</span><strong>67%</strong></div><div class="progress"><span style="width:67%"></span></div></div><footer><button data-application-detail="BRK-2026-014">Detail Pengajuan</button><button class="primary" data-tracking-detail="BRK-2026-014">Detail Tracking</button></footer></article>
<article class="application-card"><header><div><small>BRK-2026-021</small><h3>Akta Hibah</h3></div><span class="status-badge waiting">Menunggu Kelengkapan</span></header><div class="application-meta"><span>Tanggal Pengajuan<strong>12 Juni 2026</strong></span><span>Status Saat Ini<strong>Validasi Pajak</strong></span><span>Dokumen Dibutuhkan<strong>SPPT PBB terbaru</strong></span></div><div class="progress-row"><div><span>Progress</span><strong>38%</strong></div><div class="progress"><span class="amber" style="width:38%"></span></div></div><footer><button data-application-detail="BRK-2026-021">Detail Pengajuan</button><button class="primary" data-tracking-detail="BRK-2026-021">Detail Tracking</button></footer></article>
<article class="application-card"><header><div><small>BRK-2026-025</small><h3>Roya</h3></div><span class="status-badge done">Selesai</span></header><div class="application-meta"><span>Tanggal Pengajuan<strong>2 Juni 2026</strong></span><span>Tanggal Selesai<strong>9 Juni 2026</strong></span><span>Pengambilan<strong>Siap diambil</strong></span></div><div class="progress-row"><div><span>Progress</span><strong>100%</strong></div><div class="progress"><span class="green" style="width:100%"></span></div></div><footer><button data-application-detail="BRK-2026-025">Detail Pengajuan</button><button class="primary" data-tracking-detail="BRK-2026-025">Detail Tracking</button></footer></article></div></section>

<section class="dashboard-section" data-dashboard-section="new-application"><div class="page-heading"><div><p>FORM DINAMIS</p><h1>Buat Pengajuan</h1><span>Pilih layanan dan lengkapi data secara bertahap.</span></div></div><div class="wizard-shell"><div class="wizard-progress"><button class="active"><b>1</b><span>Layanan</span></button><button><b>2</b><span>Para Pihak</span></button><button><b>3</b><span>Data Objek</span></button><button><b>4</b><span>Dokumen</span></button><button><b>5</b><span>Review</span></button></div><form id="clientApplicationForm"><div class="wizard-page active" data-wizard-page="1"><h2>Pilih Jenis Layanan</h2><div class="service-tabs"><button type="button" class="active" data-service-tab="ppat">PPAT</button><button type="button" data-service-tab="notary">Notaris</button></div><div class="service-choice-grid" data-service-list></div></div><div class="wizard-page" data-wizard-page="2"><h2>Konfigurasi Para Pihak</h2><div id="partyConfiguration" class="dynamic-form-grid"></div></div><div class="wizard-page" data-wizard-page="3"><h2>Data Objek</h2><div id="objectConfiguration" class="dynamic-form-grid"></div></div><div class="wizard-page" data-wizard-page="4"><h2>Upload Dokumen Wajib</h2><p>Format PDF/JPG/PNG, maksimal 2 MB.</p><div id="requiredDocuments" class="document-upload-grid"></div></div><div class="wizard-page" data-wizard-page="5"><h2>Review & Submit</h2><div id="applicationReview" class="review-card"></div><label class="agreement"><input type="checkbox" required> Data yang diisi sudah benar.</label></div><div class="wizard-actions"><button type="button" data-wizard-prev>Sebelumnya</button><button type="button" class="primary-action" data-wizard-next>Selanjutnya</button><button type="submit" class="primary-action" data-wizard-submit hidden>Kirim Pengajuan</button></div></form></div></section>

<section class="dashboard-section" data-dashboard-section="documents"><div class="page-heading"><div><p>DOKUMEN TAMBAHAN</p><h1>Upload Dokumen</h1><span>Unggah dokumen yang diminta oleh admin atau notaris.</span></div></div><div class="request-list"><article><i>PDF</i><div><span class="status-badge waiting">Perlu Diupload</span><h3>SPPT PBB Tahun 2026</h3><p>Diperlukan untuk validasi pajak BPHTB dan PPh.</p><small>Diminta 20 Juni 2026 · BRK-2026-021</small></div><footer><label>Upload Dokumen<input type="file" hidden></label><button>Riwayat Upload</button></footer></article><article><i class="done">OK</i><div><span class="status-badge done">Sudah Diupload</span><h3>Fotokopi KTP Pasangan</h3><p>Dokumen persetujuan suami/istri.</p><small>Diupload 18 Juni 2026 · BRK-2026-014</small></div><footer><label>Ganti Dokumen<input type="file" hidden></label><button>Riwayat Upload</button></footer></article></div></section>

<section class="dashboard-section" data-dashboard-section="appointments"><div class="page-heading"><div><p>AGENDA KLIEN</p><h1>Jadwal Temu Notaris</h1><span>Kelola jadwal konsultasi, klarifikasi, dan penandatanganan.</span></div><button class="primary-action">+ Minta Jadwal</button></div><div class="appointment-list"><article><div class="appointment-date"><strong>24</strong><span>JUN 2026</span></div><div><span class="status-badge processing">Menunggu Konfirmasi</span><h3>Penandatanganan AJB</h3><p>10.00 WITA · Pertemuan Offline</p><small>Kantor Notaris/PPAT · Bawa KTP asli.</small></div><footer><button class="primary">Konfirmasi Hadir</button><button>Minta Jadwal Ulang</button><button>Tambah ke Kalender</button></footer></article><article><div class="appointment-date"><strong>02</strong><span>JUL 2026</span></div><div><span class="status-badge neutral">Terjadwal</span><h3>Konsultasi Pendirian PT</h3><p>13.30 WITA · Meeting Online</p><small>Link meeting dikirim 30 menit sebelumnya.</small></div><footer><button>Detail</button><button>Tambah ke Kalender</button></footer></article></div></section>

<section class="dashboard-section" data-dashboard-section="notifications"><div class="page-heading"><div><p>PUSAT INFORMASI</p><h1>Notifikasi</h1><span>Semua update terkait pengajuan dan jadwal Anda.</span></div><button>Tandai Semua Dibaca</button></div><div class="notification-list"><article class="unread"><i class="blue"></i><div><strong>Status berkas diperbarui</strong><p>BRK-2026-014 memasuki tahap Pengecekan Sertifikat.</p><time>Hari ini, 10:20</time></div></article><article class="unread"><i class="amber"></i><div><strong>Dokumen tambahan diminta</strong><p>Unggah SPPT PBB terbaru untuk BRK-2026-021.</p><time>Kemarin, 14:05</time></div></article><article class="unread"><i class="green"></i><div><strong>Jadwal temu dibuat</strong><p>Penandatanganan AJB pada 24 Juni 2026 pukul 10.00.</p><time>19 Juni 2026</time></div></article></div></section>

<section class="dashboard-section dashboard-settings-overlay" data-dashboard-section="settings" aria-label="Pengaturan akun"><div class="dashboard-settings-drawer"><header class="dashboard-settings-head"><div class="settings-office-logos"><img src="{{ asset('images/garuda_logo.png') }}" alt="Garuda"><img src="{{ asset('images/logo-ini-1.jpg') }}" alt="INI"><img src="{{ asset('images/PPAT.png') }}" alt="PPAT"></div><div><small>SISTEM AKUN KLIEN</small><h1>Pengaturan</h1></div><button type="button" aria-label="Tutup pengaturan" onclick="document.querySelector('[data-section=dashboard]').click()">&times;</button></header><div class="settings-profile-card"><span>KA</span><div><strong>Komang Arya Pratama</strong><small>Klien • USR-2026-0014</small><button type="button">Lihat &amp; Ubah Profil</button></div></div><div class="dashboard-settings-group"><label>Pilihan Bahasa</label><div class="settings-choice-grid"><button type="button" class="active" data-dashboard-lang="id">Bahasa Indonesia</button><button type="button" data-dashboard-lang="en">English</button></div></div><div class="dashboard-settings-group"><label>Ukuran Tampilan</label><div class="settings-choice-grid four"><button type="button" data-dashboard-view="auto">Auto</button><button type="button" data-dashboard-view="desktop">Desktop</button><button type="button" data-dashboard-view="tablet">Tablet</button><button type="button" data-dashboard-view="phone">Handphone</button></div></div><div class="dashboard-settings-group"><label>Tema Tampilan</label><div class="settings-choice-grid"><button type="button" class="active" data-dashboard-theme="light">Siang</button><button type="button" data-dashboard-theme="dark">Malam</button></div></div><div class="dashboard-settings-group"><label>Keamanan Akun</label><button class="settings-row"><span>Ubah Password<small>Terakhir diubah 30 hari lalu</small></span><b>&rsaquo;</b></button><button class="settings-row danger"><span>Logout dari Semua Perangkat<small>Keluar dari seluruh sesi aktif</small></span><b>&rsaquo;</b></button></div></div></section>
</main></div>
<div class="dashboard-modal" id="applicationDetailModal"><div class="dashboard-dialog"><button class="modal-close" data-modal-close>&times;</button><div id="applicationDetailContent"></div></div></div><div class="dashboard-modal" id="trackingDetailModal"><div class="dashboard-dialog"><button class="modal-close" data-modal-close>&times;</button><div id="trackingDetailContent"></div></div></div><div class="dashboard-modal" id="logoutModal"><div class="dashboard-dialog small-dialog"><h2>Keluar dari akun?</h2><p>Anda perlu masuk kembali untuk membuka dashboard.</p><div><button data-modal-close>Batal</button><a href="{{ route('public.home') }}">Ya, Keluar</a></div></div></div><div class="dashboard-toast"></div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script><script src="{{ asset('js/user-dashboard.js') }}?v={{ filemtime(public_path('js/user-dashboard.js')) }}" defer></script><script src="{{ asset('js/user-dashboard-i18n.js') }}?v={{ filemtime(public_path('js/user-dashboard-i18n.js')) }}" defer></script>
</body></html>
